### ISSUE TITLE
Can't log in.

### ISSUE THREAD

**Issue by Hallohannes123** [jsavargas/zspotify#101]
I didn't want to use my main acccount, so I created a new one. I can log in with my main account just fine, but my alt doesn't work for some reason. I can log into the website just fine with the same credentials. What could be the problem here?

**Comment by niclimcy** [comment]
More details, or rather logs please

**Comment by Hallohannes123** [comment]
Hey,
I managed to fix it by reinstalling it.
I tried this before, but the problem was that I also had to delete the config file and the .zspotify folder in the user directory.
I assume the issue had to do with switching accounts. Maybe you could implement a way to log out of your current account? I had to manually delete the config files to do so.
Great software, keep it up!
