### ISSUE TITLE
Need a setting to control Spotify Volume Normalisation

### ISSUE THREAD

**Issue by tjmurray** [jsavargas/zspotify#106]
My understanding is that by default, Spotify sets volume normalisation to "Normal" mode (not off by default), and that this is a per-client setting (not a per-account setting), thus would need to be configured directly in ZSpotify. Since their normalisation impacts the actual audio / audio quality, possibly introducing artefacts due to use of compressors/limiters, it would be very useful to be able to turn this setting off when using ZSpotify so that the pure audio can be streamed.

I'm not totally sure yet whether it's on or off when using current ZSpotify, but either way this is a setting we should be able to control.

Some further reading/references:

https://support.spotify.com/us/article/audio-normalization/

https://artists.spotify.com/en/help/article/loudness-normalization

**Comment by tjmurray** [comment]
Just noticed the following line on that second URL:

"Note: The web player and 3rd-party devices (e.g. speakers and TVs) don’t use loudness normalization."

So it might be that we are already safe from this (for now), but worth checking into

**Comment by tjmurray** [comment]
Okay I've now tested this and can confirm that Volume Normalisation is **not** being applied to ZSpotify streams (which is pretty much a good thing). I found a track mastered very quietly, and the ZSpotify file comes out equally quiet, whereas with Volume Normalisation turned on in the Spotify app, it plays at normal/loud volume, which confirms that it's not being applied to ZSpotify.

This issue can now be closed, but might be good to document this somewhere

**Comment by niclimcy** [comment]
Nice, maybe you can leave a comment in the librespot library about this
