### ISSUE TITLE
login not working anymore

### ISSUE THREAD

**Issue by rhovenssp** [jsavargas/zspotify#108]
When I try to use zspotify with a premium account, login doesn't function anymore. This seems to be related to changes made in the Spotify api.

The error code
`librespot.core.Session.SpotifyAuthenticationException: PremiumAccountRequired`

It has been fixed in the most recent version of librespot, as can be read at https://github.com/librespot-org/librespot-java/issues/614
Can this version be implemented in zspotify?

**Comment by gonced8** [comment]
You just need to update librespot-python to the latest version. In my case, I ran the command:
`/opt/zspotify-1.9.8/env/bin/pip install git+https://github.com/kokarare1212/librespot-python`

**Comment by tjmurray** [comment]
This is now fixed in latest commit (v2.0.4)

**Comment by vishnoe115** [comment]
> You just need to update librespot-python to the latest version. In my case, I ran the command: `/opt/zspotify-1.9.8/env/bin/pip install git+https://github.com/kokarare1212/librespot-python`

thanks bro, it fixed. very helpful comment.

**Comment by niclimcy** [comment]
Fixed in 2.0.4
