### ISSUE TITLE
Javascript variant of zspotify

### ISSUE THREAD

**Issue by PatateBoulette** [jsavargas/zspotify#11]
Hi, i think that everything is said in the title, would it be possible to create a zspotify js variant / node.js variant ?

Thanks and have a nice day. 👍

**Comment by jsavargas** [comment]
Why would I want a js version? What's wrong with the Python version? For downloads I think Python is more powerful, I downloaded plex in nodejs and I had to migrate it to Python because it was not working well

**Comment by jsavargas** [comment]
I could make a web version with docker, but I don't know how to give a start date, I have many projects in mind and little time

**Comment by Hydro001** [comment]
I'm asking because i don't know anything about Python and would like to use native code with my bot, and i can't find any wrapper

**Comment by Hydro001** [comment]
Or a least, can you tell me how i can use librespot-core in js ?

**Comment by Hydro001** [comment]
It's my other account btw, i was logged on the wrong one

**Comment by jsavargas** [comment]
Do you want to incorporate it into a bot that is made in nodejs?

**Comment by Hydro001** [comment]
Yes
