### ISSUE TITLE
incorrect api tokens "read-user-email" 

### ISSUE THREAD

**Issue by j-hertzog** [jsavargas/zspotify#13]
Hello I'm getting an error when downloading my like songs

![zspotify](https://user-images.githubusercontent.com/9396028/178388121-4b03f0a8-6cfa-4cab-bc35-d6ea747db234.png)

which is really just a 503 _insufficient authorization_ response because the request isn't being made with the right token.

the tokens that fixed the issue for me:
- `"playlist-read-private"` for the download_playlist() & download_from_user_playlist() function
- `"user-library-read"` for the client() function

Let me know if I missed anything, and I hope you have a great week!

**Comment by jsavargas** [comment]
Are you using the docker version?

**Comment by j-hertzog** [comment]
oh no, this is just running the normal python script by itself.
