### ISSUE TITLE
Error: cannon add password - login to spotify

### ISSUE THREAD

**Issue by Bob4716** [jsavargas/zspotify#136]
hi terminal show me this error:

version: 2.0.4
Login to Spotify
Username: 31qzk77yd37e2nrzbe2wx4eus3jq
Password:   [I can't write]
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\xxx\AppData\Roaming\Python\Python311\Scripts\zspotify.exe\__main__.py", line 7, in <module>
  File "C:\Users\xxx\AppData\Roaming\Python\Python311\site-packages\zspotify\__main__.py", line 950, in main
    zs.start()
  File "C:\Users\xxx\AppData\Roaming\Python\Python311\site-packages\zspotify\__main__.py", line 875, in start
    while not self.login():
              ^^^^^^^^^^^^
  File "C:\Users\xxx\AppData\Roaming\Python\Python311\site-packages\zspotify\__main__.py", line 316, in login
    return self.zs_api.login(username, password)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xxxx\AppData\Roaming\Python\Python311\site-packages\zspotify\zspotify_api.py", line 80, in login
    self.credentials).create()
                      ^^^^^^^^
  File "C:\Users\xxx\AppData\Roaming\Python\Python311\site-packages\librespot\core.py", line 1317, in create
    session.authenticate(self.login_credentials)
  File "C:\Users\xxx\AppData\Roaming\Python\Python311\site-packages\librespot\core.py", line 711, in authenticate
    self.__authenticate_partial(credential, False)
  File "C:\Users\xxxx\AppData\Roaming\Python\Python311\site-packages\librespot\core.py", line 1077, in __authenticate_partial
    raise Session.SpotifyAuthenticationException(ap_login_failed)
librespot.core.Session.SpotifyAuthenticationException: BadCredentials

Please help me

**Comment by ardoviniandrea** [comment]
I'm facing the same issue with the docker container

**Comment by Bob4716** [comment]
If anyone has a solution, please post it here.

**Comment by Timdebo** [comment]
Me too... please upload a fix.

**Comment by niclimcy** [comment]
try email, I don't think username works with librespot

**Comment by Bob4716** [comment]
> try email, I don't think username works with librespot

I try still don't work (show same error) any idea how fix it?

**Comment by alan-null** [comment]
@Bob4716 Both email and GUID based username should work fine. 
Do you actually put your credentials via prompt or you have them cached?

If you have them cached remove: `credentials.json` file and run command again to log in
If the file is not in your current directory it usually reside in `user_directory\.zspotify\credentials.json`

You could also try to remove everything and install the most recent version ( **version: 2.1.0** ). 
It helped in my case.

**Comment by Bob4716** [comment]
> @Bob4716 Both email and GUID based username should work fine. 
> 
> Do you actually put your credentials via prompt or you have them cached?
> 
> 
> 
> If you have them cached remove: `credentials.json` file and run command again to log in
> 
> If the file is not in your current directory it usually reside in `user_directory\.zspotify\credentials.json`
> 
> 
> 
> You could also try to remove everything and install the most recent version ( **version: 2.1.0** ). 
> 
> It helped in my case.

`user_directory\.zspotify\credentials.json` No in my directory file is nothing in here, I try reinstalling all

**Comment by noodleyfelix** [comment]
yeah i also can't log in

**Comment by noodleyfelix** [comment]
only way i could get it to work was going into the __main__.py file and just putting in my username and password into the login function

**Comment by Bob4716** [comment]
> only way i could get it to work was going into the __main__.py file and just putting in my username and password into the login function

Where do I change it?

**Comment by DeadskullDub** [comment]
> only way i could get it to work was going into the **main**.py file and just putting in my username and password into the login function

I fixed it using this method 

1. go to C:\Users\*yourusernamehere*\AppData\Local\Programs\Python\Python312\Lib\site-packages\zspotify
2. open "__main__" with your code editor
3. In line 241 write "username ="YOUR USER" and do the same for line 242

and then it should work properly!

**Comment by tannerhallman** [comment]
Running outside of docker is what ended up being the fix for me. Docker inherently has filesystem access limitations that require extra care to be able to operate properly.
