### ISSUE TITLE
Songs only get downloaded partally

### ISSUE THREAD

**Issue by MauritzFunke** [jsavargas/zspotify#15]
Hello, first of all thanks for your great software

Currently I have an issue regarding song downloads.
For example Wait For Me from Hablot Brown is only downloading 3:33 when the song is originally 4:06 long

**Comment by MauritzFunke** [comment]
So I had the same issue as one other person, there are to many forks of this repo. Thanks for your great work

**Comment by jsavargas** [comment]
Yes, there are many forks because the original repo was removed.  I had corrected that part that made it not download completely.  Are you using docker?  Could you share the direct link to the song to be able to do tests with that
