### ISSUE TITLE
How to change music folder permanently? 

### ISSUE THREAD

**Issue by Mehmuod** [jsavargas/zspotify#154]
I am a total programming noob and I need some help.
In v1.9.7 I could simply configure the zspotify.py file and edit this line: "ROOT_PATH = ", to change the download dir.
but in the newer version, I don't know how. I now have to set the download directory using -md every time I use zspotify.
Also, I would like to know how to change the default bitrate of the audio files downloaded from 160kbps to 128kbps.

**Comment by niclimcy** [comment]
Wrong place to ask for help, use discord server
