### ISSUE TITLE
SSLError when attempting to download some tracks caused by invalid CDN certificate

### ISSUE THREAD

**Issue by dchawisher** [jsavargas/zspotify#159]
**Environment (please complete the following information):**
 - OS: Docker
 - Python version: 
 - Launch command: zspotify (within the running container)

**Describe the bug**
When attempting to download a playlist, some tracks error out with an SSLError. From testing in my browser, it seems that one or more of the spotify CDNs has an invalid certificate. I think that when downloading a track, zspotify should be willing to use an insecure connection, or at least there should be an option to do so.

**Error Message**
HTTPSConnectionPool(host='audio4-gm-fb.spotifycdn.com', port=443): Max retries exceeded with url: [redacted] (Caused by SSLError(SSLCertVerificationError(1, "[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'audio4-gm-fb.spotifycdn.com'. (_ssl.c:1006)")))

**Comment by niclimcy** [comment]
Should be solved by latest upstream respot changes
