### ISSUE TITLE
-ls parameter returns error

### ISSUE THREAD

**Issue by axsddlr** [jsavargas/zspotify#21]
## How to reproduce
`python zspotify -ls`

## ERROR
```
Traceback (most recent call last):
  File "/home/pi/zspotify/zspotify.py", line 892, in <module>
    main()
  File "/home/pi/zspotify/zspotify.py", line 888, in main
    client()
  File "/home/pi/zspotify/zspotify.py", line 141, in client
    for song in get_saved_tracks(token):
  File "/home/pi/zspotify/zspotify.py", line 693, in get_saved_tracks
    songs.extend(resp['items'])
KeyError: 'items'
```

**Comment by jsavargas** [comment]
Something changed in the Spotify api and there are other projects that also fail doing that query, I'll try to find a solution, thank you very much

**Comment by dxvid03** [comment]
Hi, I found the solution while revisiting the spotify API

**Comment by axsddlr** [comment]
> Hi, I found the solution while revisiting the spotify API
> 
> You should change the token query on line 128 from "user-read-email" to "user-library-read"
> 
> You can find the changes here: https://developer.spotify.com/console/get-current-user-saved-tracks/

https://github.com/jsavargas/zspotify/pull/22#issue-1378267077

**Comment by jsavargas** [comment]
Thanks a lot
