### ISSUE TITLE
stops download of playlist after every song

### ISSUE THREAD

**Issue by rambosser** [jsavargas/zspotify#31]
user\anaconda3\lib\site-packages\pydub\utils.py:198: RuntimeWarning: Couldn't find ffprobe or avprobe - defaulting to ffprobe, but may not work
  warn("Couldn't find ffprobe or avprobe - defaulting to ffprobe, but may not work", RuntimeWarning)
###   SKIPPING: Arch Enemy - Doomsday Machine - Nemesis.mp3 (GENERAL DOWNLOAD ERROR)   ### [WinError 2] The system cannot find the file specified
[!] ERROR [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\Ramses/Music/ZSpotify Music/General/Arch Enemy - Doomsday Machine - Nemesis.mp3'

pls help

**Comment by jsavargas** [comment]
You use it in docker?

**Comment by rambosser** [comment]
no, i try with python anaconda

**Comment by rambosser** [comment]
if i try with regular python i get error 'items'

**Comment by rambosser** [comment]
i tried using this online tool https://colab.research.google.com/github/Ori5000/zspotifycolab/blob/main/zspotify.ipynb#scrollTo=kw3BTlN3HGzj
but that stops download at 88%

**Comment by rambosser** [comment]
uhhh. i tried installing zspotifyGUI but that didn't want to open. and now it just works in CMD... i think the problem is resolved somehow

**Comment by jsavargas** [comment]
I will try to replicate the error, since I use it on Linux and using docker and everything works fine, I will add some screenshots
