### ISSUE TITLE
Crash when download encounters a local song in playlist

### ISSUE THREAD

**Issue by Esqexn** [jsavargas/zspotify#32]
Everything downloads fine till it hits a song i added from my local library.
Any setting im missing to skip those songs?

**Comment by jsavargas** [comment]
Do you have the name to try?  Perhaps the name is too long or has strange characters

**Comment by Esqexn** [comment]
the song name is normal and not long in particular, as soon as i remove songs added from my local library from the playlist and start the download again the crashing stops. So i assume its crashing because of the fact that its not a song from spotify it is trying to download.

**Comment by jsavargas** [comment]
Oh, I didn't know that and how do you add those songs to your Spotify playlist?

**Comment by Esqexn** [comment]
In the spotify settings you can "enable local files" and add a directory (source) from where it can grab your local music.

**Comment by radio-flow** [comment]
reproduction
native ubuntu 

```
[ DETECTED PREMIUM ACCOUNT - USING VERY_HIGH QUALITY ]


###   get_song_info - FAILED TO QUERY METADATA   ###
can only concatenate str (not "NoneType") to str
###   SKIPPING SONG - FAILED TO QUERY METADATA   ###
 download_track FAILED: [None][reveals/][False][][False]
SKIPPING SONG:  local variable 'info' referenced before assignment
Traceback (most recent call last):
  File "/usr/local/bin/zspotify/zspotify.py", line 513, in get_song_info
    info = json.loads(requests.get("https://api.spotify.com/v1/tracks?ids=" + song_id +
TypeError: can only concatenate str (not "NoneType") to str

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/zspotify/zspotify.py", line 707, in download_track
    artists, album_name, name, image_url, release_year, disc_number, track_number, scraped_song_id, is_playable = get_song_info(
  File "/usr/local/bin/zspotify/zspotify.py", line 532, in get_song_info
    print(song_id,info)
UnboundLocalError: local variable 'info' referenced before assignment

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/zspotify/zspotify.py", line 892, in <module>
    main()
  File "/usr/local/bin/zspotify/zspotify.py", line 888, in main
    client()
  File "/usr/local/bin/zspotify/zspotify.py", line 162, in client
    download_track(song['track']['id'],
  File "/usr/local/bin/zspotify/zspotify.py", line 724, in download_track
    print(f" download_track FAILED: [{artists}][{album_name}][{name}][{image_url}][{release_year}][{disc_number}][{track_number}][{scraped_song_id}][{is_playable}]")
UnboundLocalError: local variable 'artists' referenced before assignment

```

**Comment by jsavargas** [comment]
> reproduction log using native ubuntu
> 
> ```
> [ DETECTED PREMIUM ACCOUNT - USING VERY_HIGH QUALITY ]
> 
> 
> ###   get_song_info - FAILED TO QUERY METADATA   ###
> can only concatenate str (not "NoneType") to str
> ###   SKIPPING SONG - FAILED TO QUERY METADATA   ###
>  download_track FAILED: [None][reveals/][False][][False]
> SKIPPING SONG:  local variable 'info' referenced before assignment
> Traceback (most recent call last):
>   File "/usr/local/bin/zspotify/zspotify.py", line 513, in get_song_info
>     info = json.loads(requests.get("https://api.spotify.com/v1/tracks?ids=" + song_id +
> TypeError: can only concatenate str (not "NoneType") to str
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/usr/local/bin/zspotify/zspotify.py", line 707, in download_track
>     artists, album_name, name, image_url, release_year, disc_number, track_number, scraped_song_id, is_playable = get_song_info(
>   File "/usr/local/bin/zspotify/zspotify.py", line 532, in get_song_info
>     print(song_id,info)
> UnboundLocalError: local variable 'info' referenced before assignment
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/usr/local/bin/zspotify/zspotify.py", line 892, in <module>
>     main()
>   File "/usr/local/bin/zspotify/zspotify.py", line 888, in main
>     client()
>   File "/usr/local/bin/zspotify/zspotify.py", line 162, in client
>     download_track(song['track']['id'],
>   File "/usr/local/bin/zspotify/zspotify.py", line 724, in download_track
>     print(f" download_track FAILED: [{artists}][{album_name}][{name}][{image_url}][{release_year}][{disc_number}][{track_number}][{scraped_song_id}][{is_playable}]")
> UnboundLocalError: local variable 'artists' referenced before assignment
> ```

I'll look at it in Ubuntu, since I use docker and the recommendation is to use it in docker, it already works without problems there, but I'll look at it in Ubuntu, thank you very much
