### ISSUE TITLE
Downloaded MP3 files have low quality cover arts

### ISSUE THREAD

**Issue by Yorisfake** [jsavargas/zspotify#33]
embedded cover arts to mp3 files are very low quality

**Comment by tjmurray** [comment]
Strongly agree (was just about the create the same issue). Full-resolution cover arts are a must, and the current 64x64px is very poor resolution. Spotify artwork is originally 640x640x, so would be great to have an option to embed artwork in full 640px resolution. 

This is a fantastic project though and by far the best of its kind that I've come across, so thank you 🙏

**Comment by Yorisfake** [comment]
I did not had this problem before, but now artwork resolution is really bad and I can't seem to figure out what could have caused it.

**Comment by jsavargas** [comment]
I am going to find out how to embed them, to improve that aspect, do they use zspotify via docker or directly?

**Comment by jsavargas** [comment]
soon I will upload a version with that change in the covers, could you try?
version 1.9.4

**Comment by tjmurray** [comment]
I'm using Docker. And yep happy to test out a new version, let me know when it's ready. Cheers!

**Comment by jsavargas** [comment]
It's ready =)

**Comment by Yorisfake** [comment]
Thanks for the fix, works like a charm now.

**Comment by jsavargas** [comment]
Could you add a screenshot of how the covers are valid?  Because I tried using mp3tag and I saw them the same 😅

**Comment by tjmurray** [comment]
I use a free software called Kid3 for analysing MP3 tags (including cover art and resolution). I'm AFK right now but if you look at the screenshot I included in the issue about "Date"/"Year" tags you'll see a screenshot from Kid3. 

Back at keyboard soon and will test 1.9.4. Cheers!

**Comment by tjmurray** [comment]
Ok 1.9.4 working perfectly now for cover arts! (at least for me). Many thanks for the quick fix. Here's a screenshot of ID3 tags from a 1.9.4 download:

<img width="835" alt="Screenshot 2022-10-15 at 13 42 23" src="https://user-images.githubusercontent.com/30073348/195989924-01246cfb-0a47-4d78-9253-fafff0286657.png">

Now it's only the empty date/year issue preventing me from setting a big batch running

**Comment by jsavargas** [comment]
yes, yesterday I was trying to make the change next to the covers, but it doesn't save, apparently the problem is in other places too, I'm going to see if I change the complement that writes them, stop.

thank you very much :D
