### ISSUE TITLE
'Year' ('Date') is missing from ID3 tags

### ISSUE THREAD

**Issue by tjmurray** [jsavargas/zspotify#34]
ID3 tags are missing the 'Year' data (I believe the tag name in ID3 is 'Date', even though it stores a year value). I notice that the ID3 tags **_do_** contain an "Original Date" tag, however most Music softwares do not recognise this (e.g. iTunes / Apple Music), so would be great to set the regular 'Date' value as well.

<img width="688" alt="Screenshot 2022-10-14 at 19 43 57" src="https://user-images.githubusercontent.com/30073348/195929253-36b1975c-1b88-4101-9fbf-51d22f93bb83.png">

**Comment by tjmurray** [comment]
Hmm so having looked into this issue, it appears to be a quirk with the 'music_tag' library that is being used (as a filetype-agnostic layer for setting audio tags). [https://pypi.org/project/music-tag/](url) (look under 'Tags' section)

Looks like music_tag only supports an internal 'year' keyword, which for mp3 files it seems to map to an "Original Date" ID3 tag when setting the tags, which is not the standard one. It doesn't seem to have any internal keyword which maps to the standard "Date" ID3 tag, which is frustrating since iTunes/Apple Music don't support "Original Date" as a tag. Not sure on best way to solve this

**Comment by tjmurray** [comment]
For others facing this, the best workaround for now is to use MP3Tag ([https://mp3tag.app/get/](url)) to do a batch processing upon your downloaded folder to import the "Original Date" date into "Date" field, as per the below:

<img width="481" alt="Screenshot 2022-10-15 at 15 24 34" src="https://user-images.githubusercontent.com/30073348/195994557-c7da737c-061e-4ad6-a52d-4caa5617c943.png">

**Comment by ganeshh123** [comment]
> For others facing this, the best workaround for now is to use MP3Tag ([https://mp3tag.app/get/](url)) to do a batch processing upon your downloaded folder to import the "Original Date" date into "Date" field, as per the below:
> 
> <img alt="Screenshot 2022-10-15 at 15 24 34" width="481" src="https://user-images.githubusercontent.com/30073348/195994557-c7da737c-061e-4ad6-a52d-4caa5617c943.png">

Thanks very much, good solution

**Comment by jsavargas** [comment]
With the current library that year doesn't work, I was trying others and that field wasn't filled in either, I have to keep doing tests but I haven't had time.  Thank you very much for your temporary solution.

**Comment by EDad-v2** [comment]
I pretty sure I've resolved this.  I made a function that tags and adds album art with mutagen directly.
It tags BOTH:
TDRC Recording time (Where Year is expected)
TDOR Original release time (Currently where Year is tagged)

music_tag can't do this, so ditching it makes sense to me.
It works for all Linux and Win apps I've tested.
I would be happy to do a pull request if there's interest.

**Comment by jsavargas** [comment]
It seems good to me, I was also looking at using another library, but I couldn't finish it because of work, I'm short of time. But I think it's excellent if you already solved it
