### ISSUE TITLE
No documentation?

### ISSUE THREAD

**Issue by Zipdox** [jsavargas/zspotify#36]
There's absolutely 0 instructions on how to use this.

**Comment by Kkspike** [comment]
To be fair, it's pretty straightforward. start the script with python and follow the instructions on screen.

**Comment by Zipdox** [comment]
I said something about credentials.json not existing. I had to create it manually, just an empty file.

**Comment by axsddlr** [comment]
> It said something about credentials.json not existing. I had to create it manually, just an empty file.

either perms issue or just an error in which you could've reported instead of saying no documentation

**Comment by Zipdox** [comment]
I fixed it and submitted a PR

**Comment by jsavargas** [comment]
Thanks, although there is a readme, apparently it was not very clear, as its pr besides the readme touches more files, I must verify it first in another branch.  

Thank you very much
