### ISSUE TITLE
Special characters in metadata don't survive (apostrophes, forward slashes, etc..)

### ISSUE THREAD

**Issue by tjmurray** [jsavargas/zspotify#38]
Apostrophes get stripped from metadata, e.g. if a track name on Spotify is "It's True", then it will become "Its True" in the metadata of the file (ID3 tag for track name)

(Other special characters may also be affected but haven't checked)

**Comment by tjmurray** [comment]
Can add forward slashes to this list, and probably more

**Comment by ajsnyde** [comment]
Created PR for this here:
https://github.com/jsavargas/zspotify/pull/40
Note that I didn't actually test this.... 😨 
But logically it looks like it should work.

**Comment by ajsnyde** [comment]
Annnnd now just reading that you meant metadata.. Woos

**Comment by jsavargas** [comment]
I will try your pr in another branch and verify the operation.  Thank you very much

**Comment by EDad-v2** [comment]
> Short answer is that most of those characters aren't legal on Windows machines.. However, I don't see why single quotes are stripped, and fixed it below. I also made the stripping of chars OS-dependent so that Linux chads don't have to deal with any stripping other than '/' or '|'.
> 
> Created PR for this here: #40 Note that I didn't actually test this.... 😨 But logically it looks like it should work.

Tested in Windows, loving those beautiful apostrophes in the filenames :)
I'll test in Linux shortly.
