### ISSUE TITLE
Converts only first 2 minutes

### ISSUE THREAD

**Issue by tippf3hlr** [jsavargas/zspotify#4]
I didn't do much testing and correct me if I'm wrong, but my downloads were capped at 2 minutes.
Also, the progress bar didn't go to 100%.

**Comment by joonas-fi** [comment]
Works for me, both for .mp3 and .ogg files, I tested ~5 songs and they're all > 2 minutes and their correct length.

Does the problem reproduce for you, for multiple different songs?

**Comment by tippf3hlr** [comment]
I'll test it again

**Comment by tippf3hlr** [comment]
I am using the main branch btw:
```
λ python ./zspotify.py

███████ ███████ ██████   ██████  ████████ ██ ███████ ██    ██
   ███  ██      ██   ██ ██    ██    ██    ██ ██       ██  ██
  ███   ███████ ██████  ██    ██    ██    ██ █████     ████
 ███         ██ ██      ██    ██    ██    ██ ██         ██
███████ ███████ ██       ██████     ██    ██ ██         ██

[ DETECTED PREMIUM ACCOUNT - USING VERY_HIGH QUALITY ]


Enter search or URL: https://open.spotify.com/track/72gv4zhNvRVdQA0eOenCal?si=e9e679e4c0454bac
Clean Bandit - What Is Love (Deluxe Edition) - Symphony (feat. Zara Larsson).mp3:  88%|▉| 6.92M/7.88M [00:01<00:00, 4.0
```

It stopped at 88% and downloaded 2:07 / 2:32.


```
λ python ./zspotify.py

███████ ███████ ██████   ██████  ████████ ██ ███████ ██    ██
   ███  ██      ██   ██ ██    ██    ██    ██ ██       ██  ██
  ███   ███████ ██████  ██    ██    ██    ██ █████     ████
 ███         ██ ██      ██    ██    ██    ██ ██         ██
███████ ███████ ██       ██████     ██    ██ ██         ██

[ DETECTED PREMIUM ACCOUNT - USING VERY_HIGH QUALITY ]


Enter search or URL: https://open.spotify.com/track/0sf12qNH5qcw8qpgymFOqD?si=b8ccd1046603410d
The Weeknd - After Hours - Blinding Lights.mp3:  88%|████████████████████████████▉    | 7.00M/7.99M [00:01<00:00, 3.98MB/s]
```

Same here, again 88%, this time 2:53 / 3:20.

**Comment by joonas-fi** [comment]
Hmm you're using premium account. I have a free account and it works. Wondering if the issue is related to all premium accounts with zspotify (though probably not, the issue I just linked uses free account).

zspotify still works flawlessly for me, weird. (I'm using the Docker image)

**Comment by cauzinnn** [comment]
I have the same problem and am using a free account (not using docker)

**Comment by jsavargas** [comment]
You can send him the link of the song that is giving you problems.  I have premium and it works fine for me (I use docker version)

**Comment by tippf3hlr** [comment]
I finally did test it again, this time with docker and a premium account, and it worked 🎉
Although i find it pretty inconvenient to run the long docker command, input your link, and then go to volumes and download your playlist as a zip file? *Then* go to containers and delete exited container and then go to volumes to delete unused volumes? what steps can i shorten here? I'm using Docker Desktop

**Comment by tippf3hlr** [comment]
Actually in #5 there is a better solution for me, but I just looked into the Docker image and `CHUNK_SIZE` is 5000 in the image.

**Comment by zippyy** [comment]
> I finally did test it again, this time with docker and a premium account, and it worked 🎉 Although i find it pretty inconvenient to run the long docker command, input your link, and then go to volumes and download your playlist as a zip file? _Then_ go to containers and delete exited container and then go to volumes to delete unused volumes? what steps can i shorten here? I'm using Docker Desktop

I am using docker as well. I ssh into the docker box, then use docker exec to get a terminal then run zpotify to download liked songs or a playlist and then detatch from the screen. works great for me and no long commands.
