### ISSUE TITLE
Error while parsing metadata for podcast

### ISSUE THREAD

**Issue by danieljg** [jsavargas/zspotify#41]
I've used this software to successfully download a few tracks and, upon attempting to download a podcast, found an error.

The podcasts in question are the episodes of "Hideo Kojima presents Brain Structure".
I made a playlist and added a few of the episodes to it.
After that I tried to download the tracks through the command line interface of zspotify.

The results follow below:

```
###   get_song_info - FAILED TO QUERY METADATA   ###
'NoneType' object is not subscriptable
6OFp3XvZVHtdKl94ybdUW7 {'tracks': [None]}
###   SKIPPING SONG - FAILED TO QUERY METADATA   ###
 download_track FAILED: [6OFp3XvZVHtdKl94ybdUW7][Hideo Kojima/][False][][False]
SKIPPING SONG:  cannot unpack non-iterable NoneType object
[!] ERROR local variable 'artists' referenced before assignment
```

Perhaps the format of the metadata is different for podcasts compared with regular tracks?

I hope this issue report is useful to increase the functionality of the software.

Best regards.

**Comment by basednerd275** [comment]
I get this error also trying to download a playlist.I got rid of the songs that had the artist removed because I thought it would fix it.It did not and still need a solution
