### ISSUE TITLE
suddenly after an error, all covers were downloaded in 64x64

### ISSUE THREAD

**Issue by NightCorpse** [jsavargas/zspotify#44]

**Comment by Yorisfake** [comment]
They fixed this, but seems like it's still bugged now

**Comment by NightCorpse** [comment]
I changed the value from 2 to 0 again and they downloaded again at 640x640

`image_url = info['tracks'][0]['album']['images'][2]['url']`

strange

**Comment by EDad-v2** [comment]
> I changed the value from 2 to 0 again and they downloaded again at 640x640
> 
> `image_url = info['tracks'][0]['album']['images'][0]['url']`
> 
> strange
> 
> #35

Yep... Seems Spotify changed it again.  Mine did the same, and your edit fixes.  For now :)

**Comment by jsavargas** [comment]
Yes, apparently they changed the method again, I will try to evaluate it looking for the highest quality and I will put that as a cover. The good thing is that I know where to touch to correct that

**Comment by NightCorpse** [comment]
> Yes, apparently they changed the method again, I will try to evaluate it looking for the highest quality and I will put that as a cover. The good thing is that I know where to touch to correct that
> 

I made a pull request with the solution to the problem, if you can take a look

**Comment by NightCorpse** [comment]
> Yes, apparently they changed the method again, I will try to evaluate it looking for the highest quality and I will put that as a cover. The good thing is that I know where to touch to correct that
> 

I made a pull request with the solution to the problem, if you can take a look
