### ISSUE TITLE
SKIP_EXISTING_FILES / SKIP_PREVIOUSLY_DOWNLOADED not working

### ISSUE THREAD

**Issue by jamesdeluk** [jsavargas/zspotify#48]
As the title says - even if the files already exist, they still download and overwrite.

This is what I'm downloading: https://open.spotify.com/show/30IEdePodyRarA7JsbGFaz

It seems `.song_archive` doesn't exist/isn't created, which might explain why `SKIP_PREVIOUSLY_DOWNLOADED` doesn't work. I tried manually adding `.song_archive` in my `ROOT_PATH` but that didn't seem to do anything. I also added some `print()`s and it seems `get_previously_downloaded()` and `add_to_archive` is never called.

**Comment by EDad-v2** [comment]
Is SKIP_EXISTING_FILES = False set to "True"?  A song can share the same filename and have a different song ID.  

add_to_archive should be called from the download_track function after each and every track is downloaded.  I'm stunned you don't have a .song_archive if you have files?  Where is your print("stuff\n")'s located?  Try one right before the add_to_archive() in the download_track function.  And one right inside one right inside the add_to_archive() function itself.

If you see your prints after a song downloads..... then check where your .song_archive is supposed to be by adding a print(archive_path + "\n") right under `archive_path = os.path.join(os.path.dirname(__file__), ROOT_PATH, '.song_archive')`  in the add_to_archive function.
If you see the entire path printed and you can't find .song_archive at that location, I'd guess you have write permission problems somehow?

Hope that helps :)

**Comment by jamesdeluk** [comment]
I did some more `print()` debugging.

It seems it's using `download_episode(episode_id_str)`, which doesn't have any checking for those variables, or does it implement the archive.

**Comment by EDad-v2** [comment]
I finally checked out your url....   I'm a idiot.  That is a podcast. download_episode() handles the download.  There seems to be no `SKIP_PREVIOUSLY_DOWNLOADED` or `SKIP_EXISTING_FILES` used in that function anywhere.  Your stuff is not protected if it happens to be the same filename.

**Comment by EDad-v2** [comment]
I hear ya...  Not only am I not a Dev...  I'm barely a Python newb.  I really need to take the time to learn the basics before I try editing/writing code lol

**Comment by EDad-v2** [comment]
I did a quick hack and came up with something that seems to be working with limited testing.

Replace the download_episode() def with:

`def download_episode(episode_id_str):
    global ROOT_PODCAST_PATH, MUSIC_FORMAT, SKIP_EXISTING_FILES, SKIP_PREVIOUSLY_DOWNLOADED

    podcast_name, episode_name = get_episode_info(episode_id_str)

    extra_paths = podcast_name + "/"
    
    check_all_time = episode_id_str in get_previously_downloaded()

    if podcast_name is None:
        print("###   SKIPPING: (EPISODE NOT FOUND)   ###")
    elif check_all_time and SKIP_PREVIOUSLY_DOWNLOADED:
        print('###   SKIPPING: ' + episode_name + ' (EPISODE ALREADY DOWNLOADED ONCE)   ###')
    else:
        filename = podcast_name + " - " + episode_name

        episode_id = EpisodeId.from_base62(episode_id_str)
        stream = SESSION.content_feeder().load(
            episode_id, VorbisOnlyAudioQuality(QUALITY), False, None)
        # print("###  DOWNLOADING '" + podcast_name + " - " +
        #      episode_name + "' - THIS MAY TAKE A WHILE ###")

        #if not os.path.isdir(ROOT_PODCAST_PATH + extra_paths):
        os.makedirs(ROOT_PODCAST_PATH + extra_paths,exist_ok=True)

        total_size = stream.input_stream.size
        data_left = total_size
        downloaded = 0
        _CHUNK_SIZE = CHUNK_SIZE
        fail = 0

        with open(ROOT_PODCAST_PATH + extra_paths + filename + ".wav", 'wb') as file, tqdm(
                desc=filename,
                total=total_size,
                unit='B',
                unit_scale=True,
                unit_divisor=1024
        ) as bar:
            while downloaded <= total_size:
                data = stream.input_stream.stream().read(_CHUNK_SIZE)
                downloaded += len(data)
                bar.update(file.write(data))
                if (total_size - downloaded) < _CHUNK_SIZE:
                    _CHUNK_SIZE = total_size - downloaded
                #print(f"[{total_size}][{_CHUNK_SIZE}] [{len(data)}] [{total_size - downloaded}] [{downloaded}]")
                if len(data) == 0 : 
                    fail += 1
                if fail > REINTENT_DOWNLOAD:
                    break
                    
            add_to_archive(episode_id_str, filename, podcast_name, episode_name)

`
set SKIP_PREVIOUSLY_DOWNLOADED and/or SKIP_EXISTING_FILES to true up top.
I take no responsibility lol

**Comment by jsavargas** [comment]
I'll check this out and if it's the same file, I can make it skip it just like it does manual downloads to generate a new version.

**Comment by jamesdeluk** [comment]
@EDad-v2, no, edits don't notify 😢 Even if you tag me it seems.

Your code doesn't look to doesn't implement `SKIP_EXISTING_FILES` yet. Do you think you'd be able to do that too?

Either way, I'll try your above code! 😄 

Yeah, Terminal seems to show Korean characters correctly, but not Command Prompt.

As for `add_to_archive`, perhaps it could use `CONFIG_DIR` instead of `ROOT_PATH` - although that is outside the scope of this issue.
