### ISSUE TITLE
Download of podcast episodes always fails at 87%

### ISSUE THREAD

**Issue by jaum20** [jsavargas/zspotify#5]
The download of podcasts always fails. I get incomplete wav files of the episodes.

![image](https://user-images.githubusercontent.com/36702273/160151881-0d3ef9c4-bfb5-45a8-96e1-c7b5d8fa5c89.png)
![image](https://user-images.githubusercontent.com/36702273/160153067-f0a0cf12-4e17-406b-af5d-701a7d71e65a.png)

I'm using w10, Python 3.10.4, ffmpeg version 2021-09-01-git-c500dc7cca-essentials_build-www.gyan.dev

**Comment by joonas-fi** [comment]
Probably related to #4

**Comment by starcroft** [comment]
Weirdly this seems to be related to, or at the very least fixed by, the CHUNK_SIZE variable.
Set at 50000 it always stops at 87%
Set at 32768 or 65536 it gets to 100%
If you remove the for loop and the bar.update parts of the code and just run `file.write(stream.input_stream.stream().read())` it also downloads to 100%.

Anyway, easy fix for me is just change CHUNK_SIZE to one of the values above!

**Comment by jsavargas** [comment]
I will do some tests and if it improves, update

**Comment by jsavargas** [comment]
If you can send me some links to the podcasts that are causing problems, I would appreciate it.

**Comment by starcroft** [comment]
Just tried this one, fails with 50000, works fine with 32768
https://open.spotify.com/episode/6CQUyuuX2R2VGLQIlSgEhQ?si=A3IwRQNOQfGSVP63xymm-A

**Comment by NathanSweet** [comment]
In the latest (as of today) the ends of my songs (not podcasts) are cut off. Eg, a 6:28 song is 5:38. Using a premium account on Windows. Every progress bar stops at 88% except a few stopping at 87%. I verified changing `CHUNK_SIZE` to `32768` fixes the problem.

**Comment by Keisori** [comment]
@NathanSweet would you mind sharing where you updated the code with that file.write code? I updated my chunksize to 32768 and am having the same 99% issue and am seeking a solution

**Comment by NathanSweet** [comment]
@Keisori Here's my file: http://n4te.com/x/4967-zspotify.py
Be sure to set `ROOT_PATH` to where you want it to write the files (I hacked it to not create a subdirectory).

**Comment by Keisori** [comment]
Thank you! looks like that fixes some of the issues, but not all of them. Still sometimes fails to download the whole song. Very interesting

**Comment by Keisori** [comment]
I wound up modding the download_episode and download_track functions replacing the for loop in the file write with a while loop
```
        total_size = stream.input_stream.size
        data_left = total_size
        with open(ROOT_PODCAST_PATH + extra_paths + filename + ".wav", 'wb') as file, tqdm(
                desc=filename,
                total=total_size,
                unit='B',
                unit_scale=True,
                unit_divisor=1024
        ) as bar:
            while data_left > 0:
                bar.update(file.write(
                    stream.input_stream.stream().read(CHUNK_SIZE)))
                data_left -= CHUNK_SIZE
```
This seems to consistently work better but I still wind up losing a second or two off the end of some songs.

**Comment by jsavargas** [comment]
Hello, you have the link of the song, to be able to do tests and perhaps leave that configuration by default

**Comment by jsavargas** [comment]
> Terminé modificando las funciones download_episode y download_track reemplazando el ciclo for en la escritura del archivo con un ciclo while que rastrea los bytes restantes
> 
> ```
>         total_size = stream.input_stream.size
>         data_left = total_size
>         with open(ROOT_PODCAST_PATH + extra_paths + filename + ".wav", 'wb') as file, tqdm(
>                 desc=filename,
>                 total=total_size,
>                 unit='B',
>                 unit_scale=True,
>                 unit_divisor=1024
>         ) as bar:
>             while data_left > 0:
>                 bar.update(file.write(
>                     stream.input_stream.stream().read(CHUNK_SIZE)))
>                 data_left -= CHUNK_SIZE
> ```
> 
> Esto parece funcionar mejor de manera consistente, pero aún termino perdiendo uno o dos segundos al final de algunas canciones.



> I wound up modding the download_episode and download_track functions replacing the for loop in the file write with a while loop that tracks remaining bytes
> 
> ```
>         total_size = stream.input_stream.size
>         data_left = total_size
>         with open(ROOT_PODCAST_PATH + extra_paths + filename + ".wav", 'wb') as file, tqdm(
>                 desc=filename,
>                 total=total_size,
>                 unit='B',
>                 unit_scale=True,
>                 unit_divisor=1024
>         ) as bar:
>             while data_left > 0:
>                 bar.update(file.write(
>                     stream.input_stream.stream().read(CHUNK_SIZE)))
>                 data_left -= CHUNK_SIZE
> ```
> 
> This seems to consistently work better but I still wind up losing a second or two off the end of some songs.

Hello, you have the link of the song, to be able to do tests and perhaps leave that configuration by default

**Comment by jsavargas** [comment]
> Just tried this one, fails with 50000, works fine with 32768 https://open.spotify.com/episode/6CQUyuuX2R2VGLQIlSgEhQ?si=A3IwRQNOQfGSVP63xymm-A

![image](https://user-images.githubusercontent.com/6886410/174695159-07398fd2-b6f2-4b3f-8b5b-043677f40866.png)

![image](https://user-images.githubusercontent.com/6886410/174695190-dd06d4c8-578f-4874-834c-ed31dd50527d.png)

without problems using a free account and a pro using docker

**Comment by jsavargas** [comment]
After many tests, this error began to appear

![image](https://user-images.githubusercontent.com/6886410/174696029-7f9a4a93-5e7d-40e7-9c3d-5353c0f69d5a.png)

**Comment by jsavargas** [comment]
> ```
>         total_size = stream.input_stream.size
>         data_left = total_size
>         with open(ROOT_PODCAST_PATH + extra_paths + filename + ".wav", 'wb') as file, tqdm(
>                 desc=filename,
>                 total=total_size,
>                 unit='B',
>                 unit_scale=True,
>                 unit_divisor=1024
>         ) as bar:
>             while data_left > 0:
>                 bar.update(file.write(
>                     stream.input_stream.stream().read(CHUNK_SIZE)))
>                 data_left -= CHUNK_SIZE
> ```

        total_size = stream.input_stream.size
        data_left = total_size
        downloaded = 0
        _CHUNK_SIZE = CHUNK_SIZE
        with open(ROOT_PODCAST_PATH + extra_paths + filename + ".wav", 'wb') as file, tqdm(
                desc=filename,
                total=total_size,
                unit='B',
                unit_scale=True,
                unit_divisor=1024
        ) as bar:
            while downloaded <= total_size:
                data = stream.input_stream.stream().read(_CHUNK_SIZE)
                downloaded += len(data)
                bar.update(file.write(data))
                if (total_size - downloaded) < _CHUNK_SIZE:
                    _CHUNK_SIZE = total_size - downloaded
                if len(data) == 0 : break

**Comment by RPGW1ZARD** [comment]
Thank you all for your support everything is working!
