### ISSUE TITLE
Album covers downloaded in low res

### ISSUE THREAD

**Issue by Daitan9** [jsavargas/zspotify#51]
I do not know why but I often got the album cover in bad resolution, for no apparent reason, maybe a bug ?

Images : 

![Capture d’écran 2022-11-21 214334](https://user-images.githubusercontent.com/63246742/203154961-5572e77e-5efe-43cd-8a66-efee3ff4bb6f.png)

![Capture d’écran 2022-11-21 214344](https://user-images.githubusercontent.com/63246742/203154985-8a7a7a08-2c46-43ed-ac4e-26acbca9d084.png)

**Comment by EDad-v2** [comment]
Yeah, Spotify changed the order of available image sizes again.
Pull request #46 addresses this and will choose the largest size even if Spotify changes it again.
It's a good fix. Hopefully it's merged into master soon. If not patch your current file until then. :)

**Comment by Daitan9** [comment]
Well, I tried to change from 0 to 2 and 2 to 0 but nothing changes.
Plus, I should add that it's only some specific album's covers that are downloaded in 64x64, others are in 640x640
Examples if you wanna try to verify : 
-Whos Ready for Tomorrow - RAT BOY
-Money Game, Pt. 2 - Ren
-usseewa - Raon
-メリッサ - PornoGraffiti

all of these are downloaded in low res in my case

**Comment by Daitan9** [comment]
After some testing, it looks like the image in the file is well in 640x640 but VLC and other players do not recognize it as it is : 

[I should precise I tested all of this with the zspotify.py from PR branch, 1.9.5)

![Capture d’écran 2022-11-22 174055](https://user-images.githubusercontent.com/63246742/203371234-33aa79d5-d377-4e32-beca-5748f48f95a1.png)

Here you can see the extracted picture on the left and vlc misunderstanding (at least it seems like it) the image resolution
The bug doesn't happen on every song (Take on me seems to not be bugged)

I'm really lost. Just to add onto this, I previously tested with Money Game Pt. 2 from Ren and at the beginning it was bugged, but then all of a sudden VLC took the correct image and displayed the right cover... Doesn't make sense to me but I hope it does to someone else !

Read on vlc forums it could be a problem with mp3 tags ?

**Comment by EDad-v2** [comment]
Please post a Spotify link to the above music file so I may troubleshoot?  Thanks

**Comment by Daitan9** [comment]
There it is : https://open.spotify.com/track/71m4Lcwxh2atmdzGjsXRlc?si=38fc8dcc8f2b4fd6

**Comment by EDad-v2** [comment]
> There it is : https://open.spotify.com/track/71m4Lcwxh2atmdzGjsXRlc?si=38fc8dcc8f2b4fd6

Thank you.  You posted while I was writing you that book above.  I tried your link as it was slightly different than the one I used and all seems well in all the viewers mentioned above. Except I didn't bother with plex.

**Comment by Daitan9** [comment]
Alright, gonna try the use_mutagen change !

**Comment by Daitan9** [comment]
Okay so I did try the `USE_MUTAGEN` change but eh.. still doesn't work but I now think it's more because of VLC and Jellyfin's image extractor;
Because if I play the files on my phone with an app other than Samsung Music (They are 64x64 in this app, **only God knows why**), the app is AIMP and THERE, it displays the correct covers. --> So it's probably just image metadata that not all players are compatible with, as weird as it is in the case of the holy VLC

Lastly, I find really weird the fact that it works on your VLC, tho you're on Linux, I doubt but maybe it changes something ?
Anyway, Tell me if I should set this as `Close with comment` or `Close as not planned`
_(haven't really touched github's issue's system in my life X)_

**Comment by EDad-v2** [comment]
I will be in the office tomorrow and will hop on my Windows computer. I have a zspotify, VLC and a few mp3 tools on it to try the PR branch on your link.  It would be interesting to me to see if I can replicate your issue.

I'm still the new guy around here. So I don't feel right recommending you close this issue. Realistically, your original issue was about low res images that won't be resolved until the code makes it into the master branch.

**Comment by Daitan9** [comment]
That's cool if you can but I'm beginning to have doubts about the issue happening on your computer
Beause just now, the covers that were displayed in 64x64 in my Samsung Music app just changed X) now some that were wrongly displayed are correctly displayed and vice versa..
So I should probably tell you to not bother too much with this "bug" since it doesn't seem to be zspotify's fault.

**Comment by gregkaqa** [comment]
Hello community I had the same problem and other but solved it. 

First fix of this problem is change 3 to 0 in:
image_url = info['tracks'][0]['album']['images'][0]['url'] and always big 640x640px art cover this is issue from this 
so its 541 line in zspotify.py 

Last issue from artcovers is not saving in mp3tag direct. always i need open aimp press f4(edit song tag) and just save. 
Solution for this is comment encoding=3 in APIC:
here: 
tags['APIC'] = APIC(                                     # APIC Attached (or linked) Picture.
                        #encoding=3, # JUST COMMENT IT AND WORK PROBLEM WITH THIS TOPIC,
                        mime='image/jpeg',
                        type=3,
etc...

After fix:
![image](https://user-images.githubusercontent.com/81391894/205523102-aca8ec01-d9fd-44e4-a8a0-aecc1c1d9b2c.png)

Before fix: 
![image](https://user-images.githubusercontent.com/81391894/205523235-82288c78-8480-4ae6-bd4a-6b816788e694.png)

In vlc is good, but i always check all about mp3 in aimp :) 

[zspotifyartcoverfixed.zip](https://github.com/jsavargas/zspotify/files/10149757/zspotifyartcoverfixed.zip)

@EDad-v2 @Daitan9 test it, but I think for me work

**Comment by EDad-v2** [comment]
@gregkaqa are you not seeing the tags in this aimp application? The encoding is supposed to be 3 for UTF-8 encoding. I don't know what encoding mutagen defaults to when no encoding is specified. I'd guess Latin. I wonder what id3 libs aimp is using? It seems the aimp site is mostly Russian so I'm not having any luck finding out.

**Comment by gregkaqa** [comment]
@EDad-v2 I dont know but after my fix cover show in windows explorer for me is better :)

**Comment by EDad-v2** [comment]
@gregkaqa Windows.  That explains much! It's unbelievable that after two decades, Windows still can't properly support id3v2.4 tags.
try saving as id3v.2.3 tags and see if that helps.
```
    #tags.save()
    tags.save(v2_version=3)
```
