### ISSUE TITLE
Podcasts with videos downloaded as mp3 will not play

### ISSUE THREAD

**Issue by spectrillsky** [jsavargas/zspotify#52]
When downloading a podcast that has video, for example this Lex Fridman podcast episode https://open.spotify.com/episode/5ERMYzdlZFDPyQ71IqoNCo?si=477fe7af46e747cb
results in a file that is <100MB, which seems like it should be an audio file but playing the file does not work

**Comment by EDad-v2** [comment]
Podcasts for some reason have a hard coded .wav file extension.  Change it to .ogg and it will play.  Only the sound is downloaded as ogg vorbis.

I've been trying to study why .wav was chosen as far as I can tell, ogg vorbis is the stream librespot-python will read.

**Comment by spectrillsky** [comment]
Thank you for the response, this would be a great update if there was a file type option. Good to know, for the time being I will be converting ogg -> mp3 as the targeted device I'm using does not play ogg files

**Comment by sherifattia** [comment]
Is there a way to download the video **_and_** the audio for podcasts like these?

**Comment by KarlRW** [comment]
> 

+1 to downloading the video as well as audio
