### ISSUE TITLE
Handle filename too long error

### ISSUE THREAD

**Issue by scarlettekk** [jsavargas/zspotify#58]
On many OSes (at least linux lol), the max filename length is 255 bytes. There are some songs with names longer than this, when "Include album name in title" is enabled (one example here https://open.spotify.com/track/0zK8Em4hCWACv0BeAVGRcr)

Zspotify should probably handle these cases and truncate the filename to be shorter - in my case, downloading liked songs, when the download fails it tries again indefinitely until the script crashes due to recursion depth limits.

**Comment by nopeless** [comment]
#60
