### ISSUE TITLE
Closes after each download

### ISSUE THREAD

**Issue by oskarparsim** [jsavargas/zspotify#69]
Program closes after downloading a song.

**Comment by nicknitewolf** [comment]
More details please

**Comment by wchorski** [comment]
I have this problem too.

Built with Docker, I run the `docker run `, search, find, and download.

once the download is complete the cli closes and the container exits.

I was hoping the CLI would stay open as I search and download songs one at a time. Also it seems a bunch of exited containers seem to stack up in the Docker graveyard. Is there a way to persist the Container so it can be used in a manager like Portainer?

**Comment by niclimcy** [comment]
Fixed https://github.com/jsavargas/zspotify/pull/142
