### ISSUE TITLE
Podcast episode failed to download

### ISSUE THREAD

**Issue by InsideOutElephant** [jsavargas/zspotify#78]
Attempting to download podcast episode with the following command:
python .\main.py -ep "https://open.spotify.com/episode/5JplhUbKVqtTzZtdvj2MaQ" -d "C:\Users\<USER>\Music\zspotify\downloads" -cd "C:\Users\<USER>\Music\zspotify\config" -pd "C:\Users\<USER>\Music\zspotify\Podcasts"

Using Windows Powershell.

The following is the console output:

    ███████ ███████ ██████   ██████  ████████ ██ ███████ ██    ██
       ███  ██      ██   ██ ██    ██    ██    ██ ██       ██  ██
      ███   ███████ ██████  ██    ██    ██    ██ █████     ████
     ███         ██ ██      ██    ██    ██    ██ ██         ██
    ███████ ███████ ██       ██████     ██    ██ ██         ██

version: 2.0.0_alpha
Migration complete from file: C:\Users\<USER>\Music\zspotify\config\.song_archive
Migration complete from file: C:\Users\<USER>\Music\zspotify\downloads\.song_archive
Migration complete from file: C:\Users\<USER>\Music\zspotify\downloads\ZSpotify Music\.song_archive
Migration complete from file: C:\Users\<USER>\Music\zspotify\Podcasts\.song_archive
Downloading What Happened To The Neandertals episode
Couldn't resolve redirect!
Eons Mysteries of Deep Time - What Happened To The Neandertals.mp3: 31.8MB [00:21, 1.58MB/s]
Converting What Happened To The Neandertals episode
###   download_track - FAILED TO DOWNLOAD   ###
Decoding failed. ffmpeg returned error code: 1

Output from ffmpeg/avlib:

ffmpeg version 5.1.2-full_build-www.gyan.dev Copyright (c) 2000-2022 the FFmpeg developers
  built with gcc 12.1.0 (Rev2, Built by MSYS2 project)
  configuration: --enable-gpl --enable-version3 --enable-static --disable-w32threads --disable-autodetect --enable-fontconfig --enable-iconv --enable-gnutls --enable-libxml2 --enable-gmp --enable-bzlib --enable-lzma --enable-libsnappy --enable-zlib --enable-librist --enable-libsrt --enable-libssh --enable-libzmq --enable-avisynth --enable-libbluray --enable-libcaca --enable-sdl2 --enable-libaribb24 --enable-libdav1d --enable-libdavs2 --enable-libuavs3d --enable-libzvbi --enable-librav1e --enable-libsvtav1 --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxavs2 --enable-libxvid --enable-libaom --enable-libjxl --enable-libopenjpeg --enable-libvpx --enable-mediafoundation --enable-libass --enable-frei0r --enable-libfreetype --enable-libfribidi --enable-liblensfun --enable-libvidstab --enable-libvmaf --enable-libzimg --enable-amf --enable-cuda-llvm --enable-cuvid --enable-ffnvcodec --enable-nvdec --enable-nvenc --enable-d3d11va --enable-dxva2 --enable-libmfx --enable-libshaderc --enable-vulkan --enable-libplacebo --enable-opencl --enable-libcdio --enable-libgme --enable-libmodplug --enable-libopenmpt --enable-libopencore-amrwb --enable-libmp3lame --enable-libshine --enable-libtheora --enable-libtwolame --enable-libvo-amrwbenc --enable-libilbc --enable-libgsm --enable-libopencore-amrnb --enable-libopus --enable-libspeex --enable-libvorbis --enable-ladspa --enable-libbs2b --enable-libflite --enable-libmysofa --enable-librubberband --enable-libsoxr --enable-chromaprint
  libavutil      57. 28.100 / 57. 28.100
  libavcodec     59. 37.100 / 59. 37.100
  libavformat    59. 27.100 / 59. 27.100
  libavdevice    59.  7.100 / 59.  7.100
  libavfilter     8. 44.100 /  8. 44.100
  libswscale      6.  7.100 /  6.  7.100
  libswresample   4.  7.100 /  4.  7.100
  libpostproc    56.  6.100 / 56.  6.100
[ogg @ 0000015de9316900] cannot find sync word
[cache @ 0000015de9316ec0] Statistics, cache hits:0 cache misses:3
cache:pipe:0: Invalid data found when processing input

5JplhUbKVqtTzZtdvj2MaQ C:\Users\<USER>\Music\zspotify\Podcasts\Eons Mysteries of Deep Time - What Happened To The Neandertals.mp3
Added to archive: Eons Mysteries of Deep Time - What Happened To The Neandertals
Set audiotags What Happened To The Neandertals
[!] ERROR [Errno 2] No such file or directory: 'C:\\Users\\<USER>\\Music\\zspotify\\Podcasts\\Eons Mysteries of Deep Time - What Happened To The Neandertals.mp3'

**Comment by jsavargas** [comment]
Thank you very much, I hope to modify this soon, I or bionded or whoever finds the problem first, since it works for some podcasts and not for others :P

**Comment by nicknitewolf** [comment]
Weird bug, eb29456df14af721030155753b5c9234a6ce4542 should solve this
