### ISSUE TITLE
Wrong file extension being written for downloaded podcast.

### ISSUE THREAD

**Issue by dezdem** [jsavargas/zspotify#87]
Hi, after downloading [this](https://open.spotify.com/episode/1cINHbHOlZJo92I63j1irR?si=sw8dkXjmQIGOMXTppYvqnw) podcast it names it as a .wav, thought it's an .mp3 file.

**Comment by nicknitewolf** [comment]
Please try again with the new version

**Comment by dezdem** [comment]
Can't download anything with 2.0.2, says "No results found", tried a podcast and a track.
1.9.9 works well

**Comment by niclimcy** [comment]
Please use the new arguments, they have changed during 1.9x to 2.0
