### ISSUE TITLE
Sanitization: only sanitize filenames, not song metadata, otherwise metadata gets spoiled (currently missing apostrophes, colons, etc)

### ISSUE THREAD

**Issue by tjmurray** [jsavargas/zspotify#97]
Title says it all. Sanitization of filenames is of course sensible and necessary, however sanitisation of song metadata (the metadata baked into the MP3 file like track name, artist, album artist, date, album name etc) is unnecessary and means users have to manually check/correct the metadata for every song that is downloaded, to reinsert missing characters.

All software that handles MP3s is fine with special characters in the metadata. My entire library is full of apostrophes, colons, etc in track names, and I've never had a single issue handling these MP3s on any piece of software.

What would make sense would be to separate the filename sanitisation from the rest of the data handling, so that MP3 metadata can be preserved in pure form.

**Comment by niclimcy** [comment]
Fixed https://github.com/jsavargas/zspotify/pull/140
