### ISSUE TITLE
When using -ls flag it raises an error

### ISSUE THREAD

**Issue by h4ppyr0gu3** [jsavargas/zspotify#98]
in zspotify/zspotify_api.py on line 454, it raises an error of key not found, the response from the api is: {'error': {'status': 403, 'message': 'Forbidden.'}}

From the documentation this error is:
  Bad OAuth request (wrong consumer key, bad nonce, expired timestamp...). Unfortunately, re-authenticating the user won't help here.

**Comment by niclimcy** [comment]
Does this happen right from the start or after a few songs in? Could you try deleting your credentials.json from ~/.zspotify and try again?

**Comment by h4ppyr0gu3** [comment]
Thanks so much

**Comment by djchoyr** [comment]
I have the same problem using the same argument 😉😉


Traceback (most recent call last):
  File "/usr/local/bin/zspotify", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/site-packages/zspotify/__main__.py", line 934, in main
    zs.start()
  File "/usr/local/lib/python3.9/site-packages/zspotify/__main__.py", line 869, in start
    self.download_liked_songs()
  File "/usr/local/lib/python3.9/site-packages/zspotify/__main__.py", line 669, in download_liked_songs
    songs = self.zs_api.get_liked_tracks()
  File "/usr/local/lib/python3.9/site-packages/zspotify/zspotify_api.py", line 462, in get_liked_tracks
    for song in resp["items"]:
KeyError: 'items'

**Comment by Hallohannes123** [comment]
> I have the same problem using the same argument 😉😉
> 
> Traceback (most recent call last): File "/usr/local/bin/zspotify", line 8, in sys.exit(main()) File "/usr/local/lib/python3.9/site-packages/zspotify/**main**.py", line 934, in main zs.start() File "/usr/local/lib/python3.9/site-packages/zspotify/**main**.py", line 869, in start self.download_liked_songs() File "/usr/local/lib/python3.9/site-packages/zspotify/**main**.py", line 669, in download_liked_songs songs = self.zs_api.get_liked_tracks() File "/usr/local/lib/python3.9/site-packages/zspotify/zspotify_api.py", line 462, in get_liked_tracks for song in resp["items"]: KeyError: 'items'

I have this exact Problem!
For now I just moved my liked songs to a playlist.

**Comment by northben** [comment]
I created a PR to fix this issue. Hope it helps someone! Thank you very much for this project.

**Comment by niclimcy** [comment]
Should be fixed by https://github.com/jsavargas/zspotify/pull/138
